from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

DATA_DIR = BASE_DIR / "data"
MODEL_DIR = BASE_DIR / "models"
LOG_DIR = BASE_DIR / "logs"

METRICS_FILE = DATA_DIR / "network_metrics.csv"
EVAL_FILE = DATA_DIR / "model_evaluation.json"
MODEL_FILE = MODEL_DIR / "predictive_models.joblib"


SAMPLE_INTERVAL = 5


PREDICTION_HORIZON_MINUTES = 5


ROLLING_WINDOW = 12

DEFAULT_PROBE_HOST = "8.8.8.8"


DEFAULT_INTERFACE_SPEED_MBPS = 100.0


LATENCY_WARNING_MS = 80.0
LATENCY_CRITICAL_MS = 150.0

PACKET_LOSS_WARNING_PCT = 2.0
PACKET_LOSS_CRITICAL_PCT = 5.0

JITTER_WARNING_MS = 30.0
JITTER_CRITICAL_MS = 60.0

UTILIZATION_WARNING_PCT = 70.0
UTILIZATION_CRITICAL_PCT = 85.0


CONGESTION_UTILIZATION_PCT = 85.0
CONGESTION_LATENCY_MS = 150.0
CONGESTION_PACKET_LOSS_PCT = 5.0
CONGESTION_JITTER_MS = 60.0

MIN_TRAIN_ROWS = 300

RANDOM_STATE = 42